            - name: filediff
  # You may pin to the exact commit or the version.
  # uses: Shopify/filediff@ada920c512dce7297703791084e5d9f2d65df418
  uses: Shopify/filediff@v0.0.4
  with:
    # The target branch to compare the diff against
    target_branch: 
    # A comma seperated list of globs to compare across branches
    dir_glob: 
    # Script to run before getting the file diff
    pre_diff_script: # optional
    # Do not render a collapsible section for the files
    file_details_open: # optional
    # Replaces previous filediff comments
    replace_comment: # optional, default is true
          
